import Head from 'next/head';
import HeroSection from '../components/HeroSection';
import { Footer } from '../components/Footer';
import {ContactForm} from "../components/ContactForm";

export default function Contact() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <ContactForm />
                <Footer />
            </main>
        </div>
    );
}
