import Head from 'next/head'
import HeroSection from '../components/hero/HeroSection'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <HeroSection />
            </main>
        </div>
    )
}
